#!/bin/bash

if [ "$(ping -q -c1 google.com &>/dev/null)" -ne 0 ]; then
	notify-send "upload.sh" "No internet connection!"
	exit 1
fi

HOST=""
DEST_PATH=""
USER=""
PASSWORD=$(zenity --password)

ftp -inv $HOST <<EOF
user $USER $PASSWORD
cd $DEST_PATH
put $1 $(basename $1)
bye
EOF

if [ $? -eq 0 ]; then
	notify-send "upload.sh" "File \"${1}\" uploaded successfully!"
else
	notify-send "upload.sh" "Error uploading file \"${1}\" :("
fi
